node = "$NODE_NAME"
version = "test"

[request]
  timeout_ms = 2002

[tracing.jaeger]
  service_name = "$NODE_NAME"

[tracing.jaeger.sampler]
  type = "probabilistic"
  param = 1.0
  # sampling_server_url = "http://localhost:6832"

[tracing.jaeger.reporter]
  log_span = true
  # queue_size = 500
  # local_agent_host_port = "localhost:6832"
  # collector_endpoint = "http://localhost:14268"

[tracing.jaeger.tags]
  node-type = "tracing-svc"

[app]
  foo = "bar"
