node = "$NODE_NAME"
version = "test"

[request]
  timeout_ms = 2002

# Stats
[stats.prometheus]
  namespace = "spine"
  addr = ""
  port = "2112"

[stats.prometheus.tags]
  environment = "development"
