// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: schedule/adapter/local/localpb/local.proto

package localpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Partition stores event keys within a specific time range
type Partition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   int64    `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Keys []string `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *Partition) Reset() {
	*x = Partition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedule_adapter_local_localpb_local_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_adapter_local_localpb_local_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_schedule_adapter_local_localpb_local_proto_rawDescGZIP(), []int{0}
}

func (x *Partition) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Partition) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Partition) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Checkpoint stores a time range. It is used to store the last load performed
// as a checkpoint to resume processing where it was left off.
type Checkpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq  uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	From int64  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To   int64  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedule_adapter_local_localpb_local_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_adapter_local_localpb_local_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_schedule_adapter_local_localpb_local_proto_rawDescGZIP(), []int{1}
}

func (x *Checkpoint) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Checkpoint) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Checkpoint) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

// A Job is a one-time task definition
type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Target  string      `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Due     int64       `protobuf:"varint,3,opt,name=due,proto3" json:"due,omitempty"`
	Data    []byte      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Options *JobOptions `protobuf:"bytes,14,opt,name=options,proto3" json:"options,omitempty"` // Interval interval = 15;
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedule_adapter_local_localpb_local_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_adapter_local_localpb_local_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_schedule_adapter_local_localpb_local_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Job) GetDue() int64 {
	if x != nil {
		return x.Due
	}
	return 0
}

func (x *Job) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Job) GetOptions() *JobOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// JobOptions contains job execution options
type JobOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetryLimit uint32 `protobuf:"varint,1,opt,name=retryLimit,proto3" json:"retryLimit,omitempty"`
	MinBackOff int64  `protobuf:"varint,2,opt,name=minBackOff,proto3" json:"minBackOff,omitempty"`
	MaxBackOff int64  `protobuf:"varint,3,opt,name=maxBackOff,proto3" json:"maxBackOff,omitempty"`
	AgeLimit   int64  `protobuf:"varint,4,opt,name=ageLimit,proto3" json:"ageLimit,omitempty"`
}

func (x *JobOptions) Reset() {
	*x = JobOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedule_adapter_local_localpb_local_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobOptions) ProtoMessage() {}

func (x *JobOptions) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_adapter_local_localpb_local_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobOptions.ProtoReflect.Descriptor instead.
func (*JobOptions) Descriptor() ([]byte, []int) {
	return file_schedule_adapter_local_localpb_local_proto_rawDescGZIP(), []int{3}
}

func (x *JobOptions) GetRetryLimit() uint32 {
	if x != nil {
		return x.RetryLimit
	}
	return 0
}

func (x *JobOptions) GetMinBackOff() int64 {
	if x != nil {
		return x.MinBackOff
	}
	return 0
}

func (x *JobOptions) GetMaxBackOff() int64 {
	if x != nil {
		return x.MaxBackOff
	}
	return 0
}

func (x *JobOptions) GetAgeLimit() int64 {
	if x != nil {
		return x.AgeLimit
	}
	return 0
}

// An Event is an occurence of a job executed at a specific time.
// There is one event per job execution.
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Due     int64  `protobuf:"varint,2,opt,name=due,proto3" json:"due,omitempty"`
	Attempt uint32 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Job     *Job   `protobuf:"bytes,15,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedule_adapter_local_localpb_local_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_adapter_local_localpb_local_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_schedule_adapter_local_localpb_local_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetDue() int64 {
	if x != nil {
		return x.Due
	}
	return 0
}

func (x *Event) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Event) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_schedule_adapter_local_localpb_local_proto protoreflect.FileDescriptor

var file_schedule_adapter_local_localpb_local_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x70, 0x62,
	0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x22, 0x43, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x42, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a,
	0x03, 0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x64, 0x75, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x2b, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x4a, 0x6f, 0x62, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x88, 0x01, 0x0a, 0x0a, 0x4a, 0x6f, 0x62, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x72, 0x65, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x12, 0x1e,
	0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x42, 0x61, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x42, 0x61, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x61, 0x0a, 0x05, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x64, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x12,
	0x1c, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x42, 0x20, 0x5a,
	0x1e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schedule_adapter_local_localpb_local_proto_rawDescOnce sync.Once
	file_schedule_adapter_local_localpb_local_proto_rawDescData = file_schedule_adapter_local_localpb_local_proto_rawDesc
)

func file_schedule_adapter_local_localpb_local_proto_rawDescGZIP() []byte {
	file_schedule_adapter_local_localpb_local_proto_rawDescOnce.Do(func() {
		file_schedule_adapter_local_localpb_local_proto_rawDescData = protoimpl.X.CompressGZIP(file_schedule_adapter_local_localpb_local_proto_rawDescData)
	})
	return file_schedule_adapter_local_localpb_local_proto_rawDescData
}

var file_schedule_adapter_local_localpb_local_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_schedule_adapter_local_localpb_local_proto_goTypes = []interface{}{
	(*Partition)(nil),  // 0: local.Partition
	(*Checkpoint)(nil), // 1: local.Checkpoint
	(*Job)(nil),        // 2: local.Job
	(*JobOptions)(nil), // 3: local.JobOptions
	(*Event)(nil),      // 4: local.Event
}
var file_schedule_adapter_local_localpb_local_proto_depIdxs = []int32{
	3, // 0: local.Job.options:type_name -> local.JobOptions
	2, // 1: local.Event.job:type_name -> local.Job
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_schedule_adapter_local_localpb_local_proto_init() }
func file_schedule_adapter_local_localpb_local_proto_init() {
	if File_schedule_adapter_local_localpb_local_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schedule_adapter_local_localpb_local_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedule_adapter_local_localpb_local_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Checkpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedule_adapter_local_localpb_local_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedule_adapter_local_localpb_local_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedule_adapter_local_localpb_local_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schedule_adapter_local_localpb_local_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schedule_adapter_local_localpb_local_proto_goTypes,
		DependencyIndexes: file_schedule_adapter_local_localpb_local_proto_depIdxs,
		MessageInfos:      file_schedule_adapter_local_localpb_local_proto_msgTypes,
	}.Build()
	File_schedule_adapter_local_localpb_local_proto = out.File
	file_schedule_adapter_local_localpb_local_proto_rawDesc = nil
	file_schedule_adapter_local_localpb_local_proto_goTypes = nil
	file_schedule_adapter_local_localpb_local_proto_depIdxs = nil
}
